INSERT INTO ORDER_DB.ORDER__BASE.T_SALES_ORDER_DETAIL (
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    ITEM_ID,
    QTY,
    TOTAL_AMOUNT,
    CREATE_DATE,
    CREATE_USER,
    PRICE
)
VALUES
    ('o-1', '2024-04-20', 'c-1', 'i-1', 3, 0, CURRENT_DATE, CURRENT_USER, 20),
    ('o-2', CURRENT_DATE, 'c-1', 'i-3', 2, 0, CURRENT_DATE, CURRENT_USER, 40),
    ('o-3', '2024-04-25', 'c-2', 'i-5', 10, 0, CURRENT_DATE, CURRENT_USER, 100),
    ('o-3', CURRENT_DATE, 'c-2', 'i-2', 20, 0, CURRENT_DATE, CURRENT_USER, 30),
    ('o-3', CURRENT_DATE, 'c-2', 'i-4', 1, 0, CURRENT_DATE, CURRENT_USER, 50),
    ('o-4', CURRENT_DATE, 'c-3', 'i-1', 8, 0, CURRENT_DATE, CURRENT_USER, 20),
    ('o-5', CURRENT_DATE, 'c-4', 'i-3', 16, 0, CURRENT_DATE, CURRENT_USER, 40),
    ('o-6', CURRENT_DATE, 'c-5', 'i-2', 31, 0, CURRENT_DATE, CURRENT_USER, 30),
    ('o-7', CURRENT_DATE, 'c-6', 'i-5', 7, 0, CURRENT_DATE, CURRENT_USER, 100);

