-- Table creation
-- Table creation script for table T_PROMOTION
CREATE TABLE IF NOT EXISTS ORDER_DB.ORDER__BASE.T_PROMOTION(
    PROMOTION_ID VARCHAR(10) PRIMARY KEY ,
    CUSTOMER_CATEGORY VARCHAR(10),
    PROMOTION_TYPE VARCHAR(10),
    PROMOTION_VALUE	NUMBER(10,2),
    COMMENT	VARCHAR(20)
)