-- Table creation script for table T_SALES_ORDER_HEADER
CREATE TABLE IF NOT EXISTS ORDER_DB.ORDER__BASE.T_SALES_ORDER_HEADER(
    ORDER_ID VARCHAR(10),
    ORDER_DATE DATE,
    STATUS VARCHAR(10),
    CUSTOMER_ID	VARCHAR(10),
    ITEM_COUNT INTEGER,
    TOTAL_AMOUNT NUMBER(12,2),
    DISCOUNT NUMBER(10,2),
    CREATE_DATE	DATE,
    CREATE_USER	VARCHAR(30),
    COUPON_CODE	VARCHAR(10)
)
